### ISSUE TITLE
Async callback is lacking error as first argument

### ISSUE THREAD

**Issue by EnzoMartin** [xxoo/node-fswin#13]
The async methods in the library don't follow the general Node callback paradigm of the first argument provided to the callback being an error object if an error occurred, or `null` if the method was successful.

I understand that you previously closed issues regarding error handling (#10), but even a raw error or simply passing null always would at least fall in line with expectations compared to other Node async methods, though it would be a breaking version change obviously.

**Comment by xxoo** [comment]
i understood that there are many good points to follow this rule. but since we don't have any detail about an error. it's just fine to determine whether error occurs with a single argument. an undefined result always means error. so i still don't think that's really necessary to break compatibility.
